authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/recipe/new/',
         views.DashboardRecipe.as_view(), name='dashboard_recipe_new'),
    path('dashboard/recipe/delete/',
         views.DashboardRecipeDelete.as_view(), name='dashboard_recipe_delete'),
    path('dashboard/recipe/<int:id>/edit',
         views.DashboardRecipe.as_view(), name='dashboard_recipe_edit'),
    path('profile/<int:id>/',
         views.ProfileView.as_view(), name='profile'),
]

menu/urls.py
from django.urls import path

from menu.views import view_menu

urlpatterns = [
    path('', view_menu),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
    path('menu/', include('menu.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('menu/', include('menu.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.RecipeListViewHome.as_view(), name='home'),
    path('recipes/search/', views.RecipeListViewSearch.as_view(), name='search'),
    path('recipes/tags/<slug:slug>/',
         views.RecipeListViewTag.as_view(), name='tags'),
    path('recipe/category/<int:category_id>/',
         views.RecipeListViewCategory.as_view(), name='category'),
    path('recipe/<int:pk>/', views.RecipeDetail.as_view(), name='recipe'),
    path('recipes/api/v1/<int:pk>/', views.RecipeDetailApi.as_view(),
         name='recipe_api_v1_detail',),
    path('recipes/api/v1/', views.RecipeListViewHomeApi.as_view(),
         name='recipe_api_v1',),
    path('recipes/theory/', views.theory, name='theory')
]

recipes/models.py
from collections import defaultdict

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.forms import ValidationError
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from tag.models import Tag

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self) -> str:
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65, verbose_name=_('Title'))
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True)

    tags = models.ManyToManyField(Tag)
    # GENERIC RELATION
    # tags = GenericRelation(Tag, related_query_name='recipes')

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('recipes:recipe', args=(self.id,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = f'{slugify(self.title)}'

        saved = super().save(*args, **kwargs)

        # Sempre retornar as alterações feitas pelas classe save
        return saved

    # Podemos tambem fazer validações dentro dos Models, e estas validações são Globais
    def clean(self, *args, **kwargs):
        error_messages = defaultdict(list)
        recipe_from_db = Recipe.objects.filter(
            title__iexact=self.title).first()

        if recipe_from_db:
            if recipe_from_db.pk != self.pk:
                error_messages['title'].append(
                    'Found recipes with the same title.')

        if error_messages:
            raise ValidationError(error_messages)

    class Meta:
        verbose_name = _('Recipe')
        verbose_name_plural = _('Recipes')

authors/forms/recipe_form.py
from collections import defaultdict

from django import forms
from django.core.exceptions import ValidationError

from recipes.models import Recipe
from utils.django_forms import add_attr
from utils.strings import is_positive_number


class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._my_errors = defaultdict(list)
        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')
        # Iremos adicionar o atributo CLASS o valor SPAN-2 logo abaixo no widgets
        # add_attr(self.fields.get('cover'), 'class', 'span-2')

    class Meta:
        model = Recipe
        db_table = ''
        fields = 'title', 'description', 'preparation_time', \
            'preparation_time_unit', 'servings', 'servings_unit', \
            'preparation_steps', 'cover'
        managed = True
        verbose_name = 'ModelName'
        verbose_name_plural = 'ModelNames'

        widgets = {
            'cover': forms.FileInput(
                attrs={
                    'class': 'span-2'
                }
            ),
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Pedaçõs', 'Pedaçõs'),
                    ('Pessoas', 'Pessoas'),
                ),
            ),
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                ),
            )
        }

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        cleaned_data = self.cleaned_data
        title = cleaned_data.get('title')

        if len(title) < 5:
            self._my_errors['title'].append('Must be have more of 5 chars ')

        if self._my_errors:
            raise ValidationError(self._my_errors)

        return super_clean

    def clean_preparation_time(self):
        field_name = 'preparation_time'
        field_value = self.cleaned_data.get(field_name)

        if not is_positive_number(field_value):
            self._my_errors[field_name].append('Must be a positive number.')

        return field_value

recipes/views/all_views.py
import os

from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.forms.models import model_to_dict
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.utils import translation
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView

from recipes.models import Recipe
from tag.models import Tag
from utils.recipes.factory import make_recipe
from utils.recipes.pagination import make_pagination, make_pagination_range

# Create your views here.

# Aqui ele vai no arquivo '.env' e prucura a chave 'PER_PAGE' e se não achar ele carregar o valor padrão 3
PER_PAGE: int = os.environ.get('PER_PAGE', 3)


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = None
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )
        qs = qs.select_related('author', 'category', 'author__profile')
        qs = qs.prefetch_related('tags', 'author__profile')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            request=self.request, queryset=ctx.get('recipes'), per_page=PER_PAGE, qty_pages=6)

        html_language = translation.get_language()
        ctx.update({
            'recipes': page_obj,
            'pagination_range': pagination_range,
            'html_language': html_language,
        })
        return ctx


class RecipeListViewHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'


class RecipeListViewHomeApi(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        rtr = super().render_to_response(context, **response_kwargs)
        recipes = self.get_context_data()['recipes']
        recipes_dict = recipes.object_list.values()
        print(recipes)
        return JsonResponse(list(recipes_dict), safe=False,)


class RecipeListViewCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        # O Underline é um alias de GETTEXT do pacote TRANSLATION
        category_trans = _('Category')
        ctx.update(
            {'title': f'{category_trans} - {ctx.get("recipes")[0].category.name}',
             'PER_PAGE': PER_PAGE}
        )

        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(category__id=self.kwargs.get(
            'category_id'))
        if not qs:
            raise Http404()

        return qs


class RecipeListViewSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()

        if not search_term:
            raise Http404()
        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term),
            ),
            is_published=True)

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()
        ctx.update({
            'page_title': f'Search for "{ search_term }"',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })
        return ctx


class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'is_detail_page': True
        })
        return context


class RecipeDetailApi(DetailView):
    model = Recipe
    context_object_name = 'recipe'

    def render_to_response(self, context, **response_kwargs):
        recipe = self.get_context_data()['recipe']
        recipe_dict = model_to_dict(recipe)

        if recipe_dict['cover']:
            recipe_dict['cover'] = self.request.build_absolute_uri() + \
                recipe_dict['cover'].url[1:]
        else:
            recipe_dict['cover'] = ''

        recipe_dict['created_at'] = str(recipe.created_at)
        recipe_dict['updated_at'] = str(recipe.updated_at)

        del recipe_dict['is_published']

        return JsonResponse(recipe_dict, safe=False,)


class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(
            slug=self.kwargs.get('slug', '')).first()
        if not page_title:
            page_title = 'No recipe found.'

        page_title = f'{page_title} - Tag '
        ctx.update({
            'page_title': f'{ page_title }',
        })
        return ctx


def theory(request, *args, **kwargs):
    x = (2.9230 * 150.30529018) * 5.20
    recipes = Recipe.objects.values('id', 'title', 'author__first_name')[:10]
    context = {
        'x': x,
        'recipes': recipes
    }

    return render(
        request,
        template_name='recipes/pages/theory.html',
        context=context
    )


"""
def home(request):
    # Duplica as receitas baseado na ID=1
    # r = Recipe.objects.get(pk=1)
    # for receitas in range(1000):
    #    r.pk = None
    #    r.title = f'Sopinha de Letras - {receitas}'
    #    r.slug = f'receita-duplicada-{receitas + 21}'
    #    r.save()

    # Altera o campo SLUG na base de dados
    # r = Recipe.objects.all()
    # for index, item in enumerate(r):
    #    item.slug = f'{item.slug}-{index}'
    #    item.save()

    # for i in r:
    #    print(i.slug)

    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    # Aqui esta pegando o parametro da QUERY STRING atraves do atributo 'page' passado pelo HTML
    try:
        current_page: int = int(request.GET.get('page', 1))
    except:
        current_page: int = 1

    # Criando a paginação, passando o QUERYSER (recipes) e o numero de itens que será exibido por páginas
    paginator = Paginator(recipes, PER_PAGE)
    page_obj = paginator.get_page(current_page)
    print(paginator.page_range)
    pagination_range = make_pagination_range(
        paginator.page_range,
        4,
        current_page
    )

    # toda a funação acima, foi reutilizada para utilizar em outras partes do programa
    # Nas outras partes do programa utilizaremos conform abaixo
    # page_obj, pagination_range = make_pagination(
    #    request=request, queryset=recipes, per_page=12, qty_pages=6)

    return render(request, 'recipes/pages/home.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
    })


def category(request, category_id: int):
    # recipes = Recipe.objects.filter(
    #     category__id=category_id, is_published=True).order_by('-id')
    # if not recipes:
    #     raise Http404(f'A Categoria ID {category_id}, não foi encontrada.')

    # Esta linha abaixo Substitui todas as linhs comentadas acima:
    recipes = get_list_or_404(Recipe.objects.filter(
        category__id=category_id, is_published=True).order_by('-id'))

    page_obj, pagination_range = make_pagination(
        request=request, queryset=recipes, per_page=PER_PAGE, qty_pages=6)

    return render(request, 'recipes/pages/category.html', context={'recipes': page_obj,
                                                                   'pagination_range': pagination_range,
                                                                   'title': f'{recipes[0].category.name} - Category'
                                                                   })


def recipe(request, id: int):
    # recipe = Recipe.objects.filter(id=id, is_published=True).first()
    # A linha abaixo substitui a linha acima, e tambem enviar uma pagina de erro se o codigo não existir
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,

    })


def search(request):
    # Nesta linha ele vai na meu formulario PARTIAL search.html no name ('q') do INPUT e envia pelo metodo GET da requisição
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    # (variavel)__icontains - como se fosse um LIKE, ele vai procurar na base de dados se contain e o (i) é para ignorar
    # Maiuscula e Minusculas
    # E o "Q" com o operador "|", é a mesma coisa que o OR
    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ),
        is_published=True
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(
        request=request, queryset=recipes, per_page=PER_PAGE, qty_pages=6)

    return render(request, 'recipes/pages/search.html', {
        'page_title': f'Search for "{ search_term }"',
        'search_term': search_term,
        'recipes': page_obj,

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css"
    integrity="sha512-RvQxwf+3zJuNwl4e0sZjQeX7kUa3o82bDETpgVCH2RiwYSZVDdFJ7N/woNigN/ldyOOoKw8584jM4plQdt8bhA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/brands.min.css"
    integrity="sha512-+oRH6u1nDGSm3hH8poU85YFIVTdSnS2f+texdPGrURaJh8hzmhMiZrQth6l56P4ZQmxeZzd2DqVEMqQoJ8J89A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css"
    integrity="sha512-uj2QCZdpo8PSbRGL/g5mXek6HM/APd7k/B5Hx/rkVFPNOxAQMXD+t+bG4Zv8OAdUpydZTU3UHmyjjiHv2Ww0PA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@900&family=Open+Sans:ital,wght@0,400;0,700;1,400&family=Roboto+Slab:wght@900&display=swap"
    rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes\css\styles.css' %}">
<link rel="stylesheet" href="{% static 'global\css\global-style.css' %}">

recipes/templates/recipes/partials/recipe.html
{% load i18n %}
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        {% if recipe.cover %}
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Temporario">
            </a>
        {% else %}
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="/media/recipes/covers/imagem_nao_disponivel.jpg"
                    alt="Temporario">
            </a>
        {% endif %}
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        
        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                {% if recipe.author.profile %}
                    <a href="{% url 'authors:profile' recipe.author.profile.id %}">
                {% endif %}
                    <i class="fa-solid fa-user"></i>
                    {% if recipe.author.first_name %}
                        {{ recipe.author.first_name }} {{ recipe.author.last_name}}
                    {% else %}
                        {{ recipe.author.username}}
                    {% endif %}
                {% if recipe.author.profile %}
                    </a>
                {% endif %}
            </span>
        {% else %}
            <span class="recipe-author-item">
                <i class="fa-solid fa-user"></i>
                Autor Desconhecido
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fa-solid fa-calendar-days"></i>
            {{recipe.created_at|date:"d/M/Y "}} às {{recipe.created_at|date:" H:i:s"}}
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fa-solid fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fa-solid fa-stopwatch"></i> {% translate 'Preparation' %}</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit}}
            </div>
        </div>

        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fa-solid fa-pizza-slice"></i> {% translate 'Servings' %}</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
            <i class="fa-solid fa-eye"></i>
            <span>{% translate 'See More' %}...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
    <div class="preparation-steps">
        {% if recipe.preparation_steps_is_html is True %}
            {{ recipe.preparation_steps|safe }}
        {% else %}
            {{ recipe.preparation_steps|linebreaksbr }}
        {% endif %}
        
        {% if recipe.tags.all %}
        <P>
            Tags:
            
            {% for tag in recipe.tags.all %}
                <a href="{% url 'recipes:tags' tag.slug %}">{{ tag.name}}, </a>
            {% endfor %}
                
        </P>
        {% endif %}
    </div>
    {% endif %}
</div>